# See: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.6
  - nightly

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.6
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(url="https://github.com/Riscure/Jlsca.git");
          Pkg.add("Documenter");
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
